# Generated by Django 4.1.7 on 2025-01-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='input_file',
            field=models.TextField(default='No file provided'),
        ),
    ]
