# Generated by Django 4.1.7 on 2025-01-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='config',
        ),
        migrations.AlterField(
            model_name='chat',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
