# Generated by Django 4.1.7 on 2025-01-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_user_is_active_user_is_staff_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.AddField(
            model_name='conversation',
            name='config',
            field=models.TextField(default="{'application_type': {'description': 'Type of application', 'options': {'web app': False, 'mobile app': True, 'api': False}}, 'test_design_techniques': {'description': 'Test Design Techniques', 'test_methodologies': {'boundary_value_analysis': True, 'equivalence_partitioning': True, 'state_transition_testing': True, 'decision_table_testing': True}}, 'testing_coverage': {'description': 'Required testing coverage', 'test_coverage_needed': {'functional_testing': True, 'nonfunctional_testing': True}, 'test_coverage_options': {'functional_testing': {'description': 'Functional testing coverage options', 'individual_field_testing': True}, 'nonfunctional_testing': {'description': 'Non-functional testing coverage options', 'performance_testing': True, 'security_testing': False, 'compatibility_testing': True, 'network_based_testing': True, 'interruption_testing': True}}}}"),
        ),
        migrations.AlterField(
            model_name='chat',
            name='input_file',
            field=models.TextField(default='No file provided'),
        ),
    ]
