# Generated by Django 4.1.7 on 2025-01-09 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_rename_cid_chat_chid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chid',
            new_name='cid',
        ),
    ]
