# Generated by Django 4.1.7 on 2025-01-09 10:04

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_conversation_conversation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='input_file',
            field=models.FileField(upload_to=chat.models.custom_upload_to),
        ),
    ]
