# Generated by Django 4.1.7 on 2025-01-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_chat_input_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/'),
        ),
    ]
