# Generated by Django 4.1.7 on 2025-01-09 18:11

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_chat_input_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.custom_upload_to),
        ),
    ]
